### ISSUE TITLE
I can't make the bot with beaver type; server doesn't respond to my request

### ISSUE THREAD

**Issue by tonymacx86PRO** [ading2210/poe-api#52] opened 2023-04-19 07:50 UTC
DEBUG:urllib3.connectionpool:https://poe.com:443 "POST /api/gql_POST HTTP/1.1" 200 89
WARNING:root:PoeBotEditMutation returned an error: Server Error | Retrying (20/20)
Traceback (most recent call last):
  File "/workspaces/poe-api-wk/main.py", line 17, in <module>
    edit_result = client.edit_bot(bot_id, handle, base_model="a2_2")
  File "/home/codespace/.python/current/lib/python3.10/site-packages/poe.py", line 459, in edit_bot
    result = self.send_query("PoeBotEditMutation", {
  File "/home/codespace/.python/current/lib/python3.10/site-packages/poe.py", line 206, in send_query
    raise RuntimeError(f'{query_name} failed too many times.')
RuntimeError: PoeBotEditMutation failed too many times.

**Comment by KevinYamazaki** [comment] 2023-04-19 08:52
Sorry to trouble you, Have you met the problem that when you run the expample file, it just stuck there like this


![error](https://user-images.githubusercontent.com/80442418/233022543-4c6cec96-0bca-48fa-927c-302179dad4a2.jpg)

**Comment by ading2210** [comment] 2023-04-19 13:42
This is a duplicate of #51, and it won't be fixed. I'll remove it from the documentation though.

**Closed by ading2210** 2023-04-19 13:42 UTC
