### ISSUE TITLE
ERROR:websocket:[Errno 104] Connection reset by peer - goodbye [Might be an old issue]

### ISSUE THREAD

**Issue by jiaigo** [ading2210/poe-api#91] opened 2023-06-02 02:10 UTC
I encountered the old problem, but for me my poe-api version is 0.4.3, just upgraded it a few days ago. (Cause  if I don't, I won't be able to retrieve the bot names through the api.)
![20230602095521](https://github.com/ading2210/poe-api/assets/42903140/531a45c3-4ed3-4567-8b76-c5f34366f1a3)

Referring to this, it may have been fixed in the old version, but why did it happen again (in ver 0.4.3)? Someone help?
https://github.com/ading2210/poe-api/issues/33#issuecomment-1510489581

**Comment by ading2210** [comment] 2023-06-02 22:55
This is a duplicate of #64.

**Closed by ading2210** 2023-06-02 22:55 UTC
Labels: duplicate
