### ISSUE TITLE
Failed to download capybara.json 

### ISSUE THREAD

**Issue by lazezo2** [ading2210/poe-api#87] opened 2023-05-30 22:23 UTC
i had that error

```
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/529nN6ESBE12znm3yWeKH/capybara.json. Retrying (10/10)...
RuntimeError: Failed to download https://poe.com/_next/data/529nN6ESBE12znm3yWeKH/capybara.json too many times.
```
and another error
```
    chat_data = self.get_bot(self.bot_names[chatbot])
                             ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'capybara'
```
any idea?

**Comment by ading2210** [comment] 2023-05-30 22:53
This is a duplicate of #86, and it has been fixed already in v0.4.2.

**Closed by ading2210** 2023-05-30 22:53 UTC
Labels: duplicate
