### ISSUE TITLE
Failed building wheel for quickjs

### ISSUE THREAD

**Issue by DOGMANTC** [ading2210/poe-api#224] opened 2023-08-15 18:46 UTC
here is the error log:
C:\Program Files\Microsoft Visual Studio\2022\Community>pip3 install poe-api
Collecting poe-api
  Obtaining dependency information for poe-api from https://files.pythonhosted.org/packages/7a/5d/44c6d6328a24f1d6f3cebb40ec98842e6afef644b2677bcd560912af8bcb/poe_api-0.5.2-py3-none-any.whl.metadata
  Using cached poe_api-0.5.2-py3-none-any.whl.metadata (20 kB)
Collecting python-socks (from poe-api)
  Using cached python_socks-2.3.0-py3-none-any.whl (53 kB)
Collecting quickjs (from poe-api)
  Using cached quickjs-1.19.2.tar.gz (455 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests[socks] in c:\python311\lib\site-packages (from poe-api) (2.30.0)
Collecting tls-client (from poe-api)
  Using cached tls_client-0.2.1-py3-none-any.whl (35.2 MB)
Collecting websocket-client (from poe-api)
  Obtaining dependency information for websocket-client from https://files.pythonhosted.org/packages/d3/a3/63e9329c8cc9be6153e919e17d0ef5b60d537fed78564872951b95bcc17c/websocket_client-1.6.1-py3-none-any.whl.metadata
  Using cached websocket_client-1.6.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests[socks]->poe-api) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests[socks]->poe-api) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests[socks]->poe-api) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests[socks]->poe-api) (2022.12.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\python311\lib\site-packages (from requests[socks]->poe-api) (1.7.1)
Using cached poe_api-0.5.2-py3-none-any.whl (72 kB)
Using cached websocket_client-1.6.1-py3-none-any.whl (56 kB)
Building wheels for collected packages: quickjs
  Building wheel for quickjs (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\quickjs
      copying quickjs\__init__.py -> build\lib.win32-cpython-311\quickjs
      running build_ext
      building '_quickjs' extension
      creating build\temp.win32-cpython-311
      creating build\temp.win32-cpython-311\Release
      creating build\temp.win32-cpython-311\Release\upstream-quickjs
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DCONFIG_VERSION=\"2021-03-27\" -DCONFIG_BIGNUM -IC:\Python311\include -IC:\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcmodule.c /Fobuild\temp.win32-cpython-311\Release\module.obj -Werror=incompatible-pointer-types
      cl : Command line error D8021 : invalid numeric argument '/Werror=incompatible-pointer-types'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quickjs
  Running setup.py clean for quickjs
Failed to build quickjs
ERROR: Could not build wheels for quickjs, which is required to install pyproject.toml-based projects

I have visual studio 2022, as is needed

**Comment by johnd0e** [comment] 2023-08-16 00:31
That is known `quickjs` issue, not related to this project.

Solution:
Make sure that here is wheel that corresponds to your Python version: https://pypi.org/project/quickjs/#files
Note that
- there is no wheel for 3.11 yet
- only x64 supported

**Comment by DOGMANTC** [comment] 2023-08-16 15:48
as in install a 3.10 version or downgrade my entire system's python
install? cause the latter will mess stuff up

**Comment by johnd0e** [comment] 2023-08-16 16:28
I have both
```
Python 3.11.4 (64-bit)  Python.Python.3.11                     3.11.4      winget
Python 3.10.11 (64-bit) Python.Python.3.10                     3.10.11     winget
```

**Comment by DOGMANTC** [comment] 2023-08-16 19:20
python.exe -m pip install --upgrade pip

**Comment by ading2210** [comment] 2023-08-16 20:18
Duplicate of #187.

**Closed by ading2210** 2023-08-16 20:18 UTC

**Comment by johnd0e** [comment] 2023-08-16 21:33
So here is the solution https://github.com/PetterS/quickjs/files/12180440/quickjs-1.19.2-cp311-cp311-win_amd64.zip

**Comment by freQuensy23-coder** [comment] 2023-08-18 02:22
> So here is the solution https://github.com/PetterS/quickjs/files/12180440/quickjs-1.19.2-cp311-cp311-win_amd64.zip
  Did somebody found 3 10 wheel for linux?
