### ISSUE TITLE
Failed to download https://poe.com

### ISSUE THREAD

**Issue by canxin121** [ading2210/poe-api#173] opened 2023-07-19 05:41 UTC
when creating a poe.Client("l_recO0Qgugq~~~"),this error occurs

https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\canxin\Documents\GitHub\poe-api\TEST.py", line 3, in <module>
    client = poe.Client("l_recO0QgugqEyfgMbEt-g%3D%3D")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canxin\Documents\GitHub\poe-api\poe-api\src\poe.py", line 123, in __init__
    self.connect_ws()
  File "C:\Users\canxin\Documents\GitHub\poe-api\poe-api\src\poe.py", line 380, in connect_ws
    self.setup_connection()
  File "C:\Users\canxin\Documents\GitHub\poe-api\poe-api\src\poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canxin\Documents\GitHub\poe-api\poe-api\src\poe.py", line 191, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canxin\Documents\GitHub\poe-api\poe-api\src\poe.py", line 53, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com too many times.

**Comment by PoetGcc** [comment] 2023-07-19 05:59
I also encountered the same problem

**Comment by Qewertyy** [comment] 2023-07-19 06:04
yes me too, but it works fine in windows

**Comment by yeqiu006** [comment] 2023-07-19 06:37
me too

**Comment by canxin121** [comment] 2023-07-19 06:39
wait,more changes in variable names should be done.This will be fixed

**Comment by CiaranYoung** [comment] 2023-07-19 07:17
Because poe updates the mechanism today

**Comment by canxin121** [comment] 2023-07-19 07:43
not yet. And it is just that the name was changed to Assistant,it is the same

**Comment by dalaolala** [comment] 2023-07-20 06:22
me too！

**Comment by ading2210** [comment] 2023-07-20 12:54
Duplicate of #153.

**Closed by ading2210** 2023-07-20 12:54 UTC

**Comment by claell** [comment] 2023-07-21 11:56
@ading2210 How is this a duplicate of #153? They seem to be completely unrelated.

**Comment by ading2210** [comment] 2023-07-23 06:27
@claell Sorry, that was a mistake. I meant issue #158.
