### ISSUE TITLE
KeyError: 'capybara'

### ISSUE THREAD

**Issue by moyanj** [ading2210/poe-api#97] opened 2023-06-03 14:02 UTC
This is the error message returned by python：

Exception in thread Thread-1 (get_bot_thread):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-2 (get_bot_thread):
Traceback (most recent call last):
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
Exception in thread Thread-3 (get_bot_thread):
Exception in thread Thread-4 (get_bot_thread):
Exception in thread Thread-5 (get_bot_thread):
    self.run()
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-7 (get_bot_thread):
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
    self.run()
    self.run()
Exception in thread Thread-6 (get_bot_thread):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
Traceback (most recent call last):
    chat_data = self.get_bot(bot["displayName"])
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
    chat_data = self.get_bot(bot["displayName"])
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    chat_data = self.get_bot(bot["displayName"])
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
    chat_data = self.get_bot(bot["displayName"])
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
    chat_data = self.get_bot(bot["displayName"])
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread
    chat_data = self.get_bot(bot["displayName"])
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
    chat_data = self.get_bot(bot["displayName"])
                             ~~~^^^^^^^^^^^^^^^
KeyError: 'displayName'
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/req.py", line 6, in <module>
    for chunk in client.send_message("capybara", message):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 332, in send_message
    "chatId": self.bots[chatbot]["chatId"],
              ~~~~~~~~~^^^^^^^^^
KeyError: 'capybara'

**Comment by maxcurrent420** [comment] 2023-06-03 19:41
I have this error too when using the sample scripts.

**Comment by ading2210** [comment] 2023-06-03 22:41
I can't reproduce this. Try updating your version of the library perhaps?

**Comment by Anandkrishna34** [comment] 2023-06-04 06:47
> This is the error message returned by python：
> 
> Exception in thread Thread-1 (get_bot_thread): Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner Exception in thread Thread-2 (get_bot_thread): Traceback (most recent call last): self.run() File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run Exception in thread Thread-3 (get_bot_thread): Exception in thread Thread-4 (get_bot_thread): Exception in thread Thread-5 (get_bot_thread): self.run() Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner self._target(*self._args, **self._kwargs) Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner Exception in thread Thread-7 (get_bot_thread): self.run() self._target(*self._args, **self._kwargs) File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread self.run() self.run() Exception in thread Thread-6 (get_bot_thread): File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run Traceback (most recent call last): chat_data = self.get_bot(bot["displayName"]) File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread chat_data = self.get_bot(bot["displayName"]) ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner self.run() File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run self._target(*self._args, **self._kwargs) chat_data = self.get_bot(bot["displayName"]) File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread self.run() self._target(*self._args, **self._kwargs) File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 975, in run ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread chat_data = self.get_bot(bot["displayName"]) ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' chat_data = self.get_bot(bot["displayName"]) ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' self._target(*self._args, **self._kwargs) File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread self._target(*self._args, **self._kwargs) File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 159, in get_bot_thread chat_data = self.get_bot(bot["displayName"]) ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' chat_data = self.get_bot(bot["displayName"]) ~~~^^^^^^^^^^^^^^^ KeyError: 'displayName' Traceback (most recent call last): File "/data/data/com.termux/files/home/req.py", line 6, in for chunk in client.send_message("capybara", message): File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/poe.py", line 332, in send_message "chatId": self.bots[chatbot]["chatId"], ~~~~~~~~~^^^^^^^^^ KeyError: 'capybara'

I too had the same issue. You can update poe by running `pip install --upgrade poe-api` or uninstalling and installing again using `pip uninstall poe-api` and `pip install poe-api`

**Comment by HIT-Owen** [comment] 2023-06-07 06:28
Update poe-api to the latest version, which can fix this issue

**Comment by ading2210** [comment] 2023-06-07 21:23
@moyanj @maxcurrent420 
Can you update your version of the library like others have suggested and check if that fixes it?

**Comment by maxcurrent420** [comment] 2023-06-09 11:37
Yes that fixed it.

**Comment by mak448a** [comment] 2023-06-09 19:15
@ading2210 You should close this issue since it's fixed

**Closed** 2023-06-09 21:09 UTC
Labels: bug
