### ISSUE TITLE
Invalid token or no bots are available

### ISSUE THREAD

**Issue by Anandkrishna34** [ading2210/poe-api#107] opened 2023-06-09 02:29 UTC
I installed kiwi browser and downloaded cookie editor extebstion and put it in my code and there is error called invalidtoken or no bots are available

**Comment by pixia1234** [comment] 2023-06-09 09:01
see issue #105

**Comment by ading2210** [comment] 2023-06-09 20:15
This is a duplicate of #105.

**Closed by ading2210** 2023-06-09 20:15 UTC
