### ISSUE TITLE
[Server Cannot Run Properly]Seeking Expert Solutions

### ISSUE THREAD

**Issue by Summercuisine** [ading2210/poe-api#176] opened 2023-07-19 16:08 UTC
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...

**Comment by Summercuisine** [comment] 2023-07-19 16:24
> 

没有解决掉！

**Comment by canxin121** [comment] 2023-07-19 23:19
把请求头换成服务器的请求头试试，等我用colab测试下我代码

**Comment by Summercuisine** [comment] 2023-07-20 01:46
> 把请求头换成服务器的请求头试试，等我用colab测试下我代码

还是不行

**Comment by CatAnd-Dog** [comment] 2023-07-20 05:03
RuntimeError: Failed to download https://poe.com too many times.
Have you seen this error ?

**Comment by ZikaiSun** [comment] 2023-07-20 05:26
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
Failed to connect to poe due to Failed to download https://poe.com too many times.
hpi-T5PLAwEAKXf3X7sD0g%3D%3D failed: Failed to download https://poe.com too many times.
hpi-T5PLAwEAKXf3X7sD0g%3D%3D: raised KeyError.

I have the same issue, All my three server have this problem... any idea how to solve it? is my server's ip banned? How can I test that?

**Comment by CiaranYoung** [comment] 2023-07-20 06:09
![image](https://github.com/ading2210/poe-api/assets/87439103/90b6e25d-af53-42c7-9176-ce1980a87c5b)
I have the same problem, I am running on replit, so what part of poe-api needs to be modified

**Comment by ading2210** [comment] 2023-07-20 12:55
Duplicate of #158.

**Closed by ading2210** 2023-07-20 12:55 UTC
