### ISSUE TITLE
Stuck at 'Subscribing to mutations'

### ISSUE THREAD

**Issue by xybovbnrx88807** [ading2210/poe-api#104] opened 2023-06-06 14:46 UTC
```shell
[2023-06-06 22:39:09.830][INFO][root] Setting up session...
[2023-06-06 22:39:09.830][INFO][root] Downloading next_data...
[2023-06-06 22:39:12.089][INFO][root] Downloading channel data...
[2023-06-06 22:39:12.432][INFO][root] Downloading all bots...
[2023-06-06 22:39:14.066][INFO][root] Subscribing to mutations
[2023-06-06 22:39:21.193][ERROR][websocket] Connection to remote host was lost. - goodbye
[2023-06-06 22:39:21.194][WARNING][root] Websocket closed with status None: None
```
It stucks on 'Subscribing to mutations' and then crashes, any idea?

Version: poe-api 0.4.4

Python 3.10

**Comment by ading2210** [comment] 2023-06-07 05:27
I can't seem to reproduce this.

**Comment by SuperLiveYou** [comment] 2023-06-07 05:35
> I can't seem to reproduce this. Are you using the library with a proxy?

At least I enabled proxy parameter settings when using it

**Comment by xybovbnrx88807** [comment] 2023-06-07 09:00
> I can't seem to reproduce this. Are you using the library with a proxy?

I was running it with and without proxy, it's the same behaviour. 

However, this morning the problem disappeared and I didn't change anything.

Is it the POE;s server that's causing the problem? What exactly does 'Subscribing to mutations' mean?

**Comment by powellnorma** [comment] 2023-06-07 09:45
> Is it the POE;s server that's causing the problem?

I tested it on the fronted, and it worked fine there. (There was a time period in which the fronted was not accessible (error 500), but that period was much smaller (maybe ~30min) than this problem persisted (3-4 hours))

> What exactly does 'Subscribing to mutations' mean?

A POST Request is used that tells the server to send us mutations over the websocket connection (see [here](https://github.com/ading2210/poe-api/blob/9e647160bf49ef555013e4e0d95e97f4dc1ac994/poe-api/src/poe.py#L325)) . I guess that POST Request is where it got stock?

**Comment by ading2210** [comment] 2023-06-07 21:21
This may be a duplicate of #50.

**Comment by ading2210** [comment] 2023-06-08 02:33
Also, I'm planning on overhauling the websocket implementation, along with implementing a fallback non-websocket mode.

**Closed** 2023-06-08 13:26 UTC
Labels: bug
