### ISSUE TITLE
I have been banned for two accounts. Has Poe changed the protocol?

### ISSUE THREAD

**Issue by SuperLiveYou** [ading2210/poe-api#94] opened 2023-06-02 18:03 UTC
-

**Comment by SuperLiveYou** [comment] 2023-06-02 18:05
Or is it my problem? I am using it as a robot and may request more than twenty times a minute

**Comment by ading2210** [comment] 2023-06-02 22:52
This is a duplicate of #88.

**Closed by ading2210** 2023-06-02 22:52 UTC
