### ISSUE TITLE
If there is no message for a long time, the connection will be broken

### ISSUE THREAD

**Issue by Barbery** [ading2210/poe-api#9] opened 2023-04-03 00:34 UTC
Is there any way to keep it active all the time?

error msg:
```
  File "/usr/local/lib/python3.9/dist-packages/poe.py", line 260, in send_message
    raise RuntimeError("Response timed out.")
RuntimeError: Response timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatgpt/chatgpt.py", line 82, in askViaPoe
    for data in client.send_message(node, q, with_chat_break=False):
  File "/usr/local/lib/python3.9/dist-packages/poe.py", line 260, in send_message
    raise RuntimeError("Response timed out.")
RuntimeError: Response timed out.
```

**Comment by ading2210** [comment] 2023-04-03 01:14
You can specify the `timeout` argument on `client.send_message` to increase the timeout if you need to do so.
```python3
for chunk in client.send_message("capybara", "your prompt", timeout=60):
  pass
```

**Comment by Barbery** [comment] 2023-04-03 15:44
more logs
```
WARNING:root:Websocket returned error: 'messages'
ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f2fdda83dc0>>: 'messages'

WARNING:root:Websocket returned error: Connection to remote host was lost.
ERROR:websocket:Connection to remote host was lost. - goodbye

```

**Comment by zhanbao2000** [comment] 2023-04-04 18:03
same issue

repeat this log:

```
ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f585aca1130>>: 'messages'
WARNING:root:Websocket returned error: 'messages'
```

when use `send_message`, I can't receive result, but on the website  I can see the message I sent and the bot's reply.

**Comment by ading2210** [comment] 2023-04-05 03:30
I'm able to reproduce this, and I'm currently working on a fix.

**Comment by jijunhao** [comment] 2023-04-05 03:35
new issue
repeat this log:
```
ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x000002218714F850>>: 'data'
WARNING:root:Websocket returned error: 'data'
```
I think they are caused by the same issue. Yesterday it was a ‘message’, and now it's ‘data’.

**Comment by bk1412** [comment] 2023-04-05 03:47
> 

same, now totally not working, i think because poe web has changed something

**Comment by ading2210** [comment] 2023-04-05 03:54
This has hopefully been fixed in 0.2.5.

**Closed by ading2210** 2023-04-05 03:54 UTC
Labels: bug

**Comment by nnhieu97** [comment] 2023-04-13 10:50
It seems like this error is still present in the current version. I received a similar error message when using version 0.2.9.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/poe.py", line 285, in send_message
    message = self.message_queues[human_message_id].get(timeout=timeout)
  File "/usr/local/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/poe.py", line 289, in send_message
    raise RuntimeError("Response timed out.")
RuntimeError: Response timed out.
```

**Comment by ading2210** [comment] 2023-04-14 03:39
@nnhieu97 Check issue #33 for updates regarding this bug in the current version.

**Comment by notBradPitt** [comment] 2023-05-22 06:17
> @nnhieu97 Check issue #33 for updates regarding this bug in the current version.

I'm using the latest version and is still facing similar problem. Though it doesn't give out any error, it just get stucks not displaying anything. I've fixed the problem by refreshing the `client` every 30 seconds, but I'm wondering what the limit is.
