### ISSUE TITLE
KeyError: 'displayName'

### ISSUE THREAD

**Issue by riusksk** [ading2210/poe-api#99] opened 2023-06-04 13:57 UTC
```
python .\send_message.py
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...

Exception in thread Thread-1 (get_bot_thread):
Traceback (most recent call last):
....
      self._target(*self._args, **self._kwargs)
  File "C:\Users\riusk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\poe.py", line 159, in get_bot_thread
    chat_data = self.get_bot(bot["displayName"])
KeyError: 'displayName'
```

bot_list:

`[{'botId': 3002, 'id': 'Qm90OjMwMDI='}, {'botId': 3007, 'id': 'Qm90OjMwMDc='}, {'botId': 1008, 'id': 'Qm90OjEwMDg='}, {'botId': 1009, 'id': 'Qm90OjEwMDk='}, {'botId': 1006, 'id': 'Qm90OjEwMDY='}, {'botId': 3004, 'id': 'Qm90OjMwMDQ='}, {'botId': 1267670, 'id': 'Qm90OjEyNjc2NzA='}, {'botId': 1009984, 'id': 'Qm90OjEwMDk5ODQ='}, {'botId': 1106253, 'id': 'Qm90OjExMDYyNTM='}, {'botId': 4000, 'id': 'Qm90OjQwMDA='}, {'botId': 3003, 'id': 'Qm90OjMwMDM='}]`

**Comment by ading2210** [comment] 2023-06-04 21:04
This is a duplicate of #86 and it has already been fixed. Update your version of the library.

**Closed by ading2210** 2023-06-04 21:04 UTC
