### ISSUE TITLE
Error Download too many times

### ISSUE THREAD

**Issue by phamxtien** [ading2210/poe-api#143] opened 2023-07-04 00:01 UTC
Failed to download https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/chinchilla.json too many times.

**Comment by phamxtien** [comment] 2023-07-04 00:30
Fix by:
```
if "payload" in data["pageProps"]:
      # chat_data = data["pageProps"]["payload"]["chatOfBotDisplayName"]    << line 239
      chat_data = data["pageProps"]["payload"]["chatOfBotHandle"]
    else:
      # chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
      chat_data = data["pageProps"]["data"]["chatOfBotHandle"]
```

**Comment by legit-programmer** [comment] 2023-07-04 00:55
I am having the some issue but adding this isn't working...

> Fix by:
> 
> ```
> if "payload" in data["pageProps"]:
>       # chat_data = data["pageProps"]["payload"]["chatOfBotDisplayName"]    << line 239
>       chat_data = data["pageProps"]["payload"]["chatOfBotHandle"]
>     else:
>       # chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
>       chat_data = data["pageProps"]["data"]["chatOfBotHandle"]
> ```

I am having the same issue...

**Comment by phamxtien** [comment] 2023-07-04 01:00
![image](https://github.com/ading2210/poe-api/assets/33739597/5c379b0e-6b2e-453c-9474-88b062a34325)

**Comment by ading2210** [comment] 2023-07-04 01:59
Duplicate of #141

**Closed by ading2210** 2023-07-04 01:59 UTC
Labels: duplicate
