### ISSUE TITLE
Server returned a status code of 400

### ISSUE THREAD

**Issue by MoriSummerz** [ading2210/poe-api#41] opened 2023-04-15 09:46 UTC
It seems that poe changed the query mechanism and the current version of th library does not pass the authentication.
Traceback:
```
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
Traceback (most recent call last):
   File "./script.py", line 14, in <module>
     client = poe.Client("REDACTED")
   File "lib/python3.9/site-packages/poe.py", line 79, in __init__
     self.subscribe()
   File "lib/python3.9/site-packages/poe.py", line 160, in subscribe
     result = self.send_query("SubscriptionsMutation", {
   File "lib/python3.9/site-packages/poe.py", line 147, in send_query
     r = request_with_retries(self.session.post, self.gql_url, json=payload, headers=self.gql_headers)
   File "lib/python3.9/site-packages/poe.py", line 37, in request_with_retries
     raise RuntimeError(f"Failed to download {url} too many times.")
 RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.
 ```

**Comment by TheLime1** [comment] 2023-04-15 12:15
api work fine for me , make sure to upgrade the package to 0.2.10 :
`pip install --upgrade poe-api
`

**Comment by TheLime1** [comment] 2023-04-15 13:37
#39

**Comment by ading2210** [comment] 2023-04-15 20:48
This is a duplicate of #37.

**Closed by ading2210** 2023-04-15 20:48 UTC
Labels: duplicate
