### ISSUE TITLE
V0.4.11  Failed to download https://poe.com too many times.

### ISSUE THREAD

**Issue by PoetGcc** [ading2210/poe-api#179] opened 2023-07-21 02:09 UTC
https://github.com/ading2210/poe-api/pull/174 is work, but when update poe-api 0.4.11，don't work

**Comment by buaabarty** [comment] 2023-07-21 02:26
I have the same situation.

**Comment by claell** [comment] 2023-07-21 12:07
For me, it doesn't matter. Both 0.4.10 and 0.4.11 give this error. Yesterday, less than 24 hours ago, it still worked with 0.4.10 for me.

**Comment by claell** [comment] 2023-07-21 12:10
Seems to be a possible duplicate of #173, though.

**Comment by noseon** [comment] 2023-07-21 13:44
https://github.com/canxin121/poe-api he changed something and it's working now I don't know why the author here didn't merge the code

**Comment by LiMingchen159** [comment] 2023-07-21 17:00
I got the same error.

**Comment by ading2210** [comment] 2023-07-22 08:49
Duplicate of #158.

**Closed by ading2210** 2023-07-22 08:49 UTC
